fragment ProtocolEventCategory on ProtocolEventCategory {
  ...BaseCategory
  ...BaseNodeCategory
  label
  ageName
  label
  description
  image {
    ...MediaStore
  }
  inputs {
    ...EventRole
  }
  outputs {
    ...EventRole
  }
  propertyDefinitions {
     ...PropertyDefinition
  }
}

fragment ListProtocolEventCategory on ProtocolEventCategory {
  ...BaseListCategory
  ...BaseNodeCategory
  label
  inputs {
    ...EventRole
  }
  outputs {
    ...EventRole
  }
  propertyDefinitions {
     ...PropertyDefinition
  }
}
