fragment StructureRelationCategory on StructureRelationCategory {
  ...BaseEdgeCategory
  ...BaseCategory
  sourceDescriptor {
    ...StructureDescriptor
  }
  targetDescriptor {
    ...StructureDescriptor
  }
   propertyDefinitions {
     ...PropertyDefinition
   }
  ageName
  label
  description
  image {
    ...MediaStore
  }
  pinned
}

fragment ListStructureRelationCategory on StructureRelationCategory {
  ...BaseListCategory
  ...BaseListEdgeCategory
  sourceDescriptor {
    ...StructureDescriptor
  }
  targetDescriptor {
    ...StructureDescriptor
  }
  propertyDefinitions {
     ...PropertyDefinition
   }
  label
}

fragment ListStructureRelationCategoryWithGraph on StructureRelationCategory {
  ...ListStructureRelationCategory
  graph {
    id
    name
    description
  }
}
