projects:
  kraph:
    schema: "graphql/schemas/kraph.graphql"
    documents: "graphql/kraph/**/*.graphql"

  mikro:
    schema: "graphql/schemas/mikro.graphql"
    documents: "graphql/mikro-next/**/*.graphql"

  rekuest:
    schema: "graphql/schemas/rekuest.graphql"
    documents: "graphql/rekuest/**/*.graphql"

  dokuments:
    schema: "graphql/schemas/dokuments.graphql"
    documents: "graphql/dokuments/**/*.graphql"

  fluss:
    schema: "graphql/schemas/fluss.graphql"
    documents: "graphql/fluss/**/*.graphql"

  kabinet:
    schema: "graphql/schemas/kabinet.graphql"
    documents: "graphql/kabinet/**/*.graphql"

  bank:
    schema: "graphql/schemas/bank.graphql"
    documents: "graphql/bank/**/*.graphql"
