fragment OpticalElement on OpticalElement {
  id
  label
  kind
  manufacturer
  model
  pose {
    position {
      x
      y
      z
    }
    orientation {
      rx
      ry
      rz
    }
  }
  ports {
    id
    name
    role
    channel
    spectrum {
      ...Spectrum
    }
  }
}

fragment Spectrum on Spectrum {
  min
  max
}

fragment DetectorElement on DetectorElement {
  ...OpticalElement
  nepdWPerSqrtHz
  gain
}

fragment LaserElement on LaserElement {
  ...OpticalElement
  nominalWavelength
  power
  pulseKind
  repetitionRate
}

fragment CCDElement on CCDElement {
  ...OpticalElement
  pixelSize
  resolution
}

fragment ObjectiveElement on ObjectiveElement {
  ...OpticalElement
  magnification
  numericalAperture
  workingDistance
  immersionMedium
}

fragment FilterElement on FilterElement {
  ...OpticalElement
  label
}

fragment OtherElement on OtherElement {
  ...OpticalElement
  label
}

fragment OtherSourceElement on OtherSourceElement {
  ...OpticalElement
  channel
}

fragment MirrorElement on MirrorElement {
  ...OpticalElement
  angleDeg
  band {
    ...Spectrum
  }
}

fragment BeamSplitterElement on BeamSplitterElement {
  ...OpticalElement
  rFraction
  tFraction
  band {
    ...Spectrum
  }
}

fragment LensElement on LensElement {
  ...OpticalElement
  focalLength
}

fragment PinholeElement on PinholeElement {
  ...OpticalElement
  diameter
}

fragment SampleElement on SampleElement {
  ...OpticalElement
  label
}

fragment LampElement on LampElement {
  ...OpticalElement
  lampType
}

fragment ApertureElement on ApertureElement {
  ...OpticalElement
  diameter
}

fragment PolarizerElement on PolarizerElement {
  ...OpticalElement
  angleDeg
}

fragment ShutterElement on ShutterElement {
  ...OpticalElement
  isOpen
}

fragment WaveplateElement on WaveplateElement {
  ...OpticalElement
  angleDeg
  retardance
}

fragment LightEdge on LightEdge {
  id
  sourceElementId
  sourcePortId
  targetElementId
  targetPortId
  medium
  pathLength
  beam {
    wavelength
  }
}

fragment LightpathGraph on LightpathGraph {
  elements {
    __typename
    ...OpticalElement
    ...SampleElement
    ...OtherSourceElement
    ...DetectorElement
    ...MirrorElement
    ...BeamSplitterElement
    ...LensElement
    ...ObjectiveElement
    ...LaserElement
    ...FilterElement
    ...OtherElement
    ...PinholeElement
    ...CCDElement
    ...LampElement
    ...ApertureElement
    ...PolarizerElement
    ...ShutterElement
    ...WaveplateElement
  }
  edges {
    ...LightEdge
  }
}
