query Workspace($id: ID!) {
  workspace(id: $id) {
    ...Workspace
  }
}

query Workspaces(
  $filters: WorkspaceFilter
  $pagination: OffsetPaginationInput
  $ordering: [WorkspaceOrder!]
) {
  workspaces(filters: $filters, pagination: $pagination, ordering: $ordering) {
    ...ListWorkspace
  }
}

query WorkspaceCarousel(
  $pagination: OffsetPaginationInput
  $filters: WorkspaceFilter
  $ordering: [WorkspaceOrder!]
) {
  workspaces(pagination: $pagination, filters: $filters, ordering: $ordering) {
    ...CarouselWorkspace
  }
}
