query ListBankConnections($filters: BankConnectionFilter, $pagination: OffsetPaginationInput) {
  bankConnections(filters: $filters, pagination: $pagination) {
    ...ListBankConnection
  }
}

query GetBankConnection($id: ID!) {
  bankConnection(id: $id) {
    ...BankConnection
  }
}

query BankInstitutions($provider: ID!, $country: String!) {
  bankInstitutions(provider: $provider, country: $country) {
    name
    country
    logo
    bic
    maximumConsentDays
  }
}

query AuthSession($state: String!) {
  authSession(state: $state) {
    ...AuthSession
  }
}
