mutation CreateCategory($input: CreateCategoryInput!) {
  createCategory(input: $input) {
    ...Category
  }
}

mutation UpdateCategory($input: UpdateCategoryInput!) {
  updateCategory(input: $input) {
    ...Category
  }
}

mutation DeleteCategory($id: ID!, $reassignTo: ID, $dryRun: Boolean! = false) {
  deleteCategory(id: $id, reassignTo: $reassignTo, dryRun: $dryRun) {
    ...CategoryDeletion
  }
}

mutation SeedDefaultCategories {
  seedDefaultCategories {
    ...ListCategory
  }
}

mutation SyncBaseCategories {
  syncBaseCategories {
    ...ListCategory
  }
}

mutation RestoreBaseCategory($key: String!) {
  restoreBaseCategory(key: $key) {
    ...ListCategory
  }
}

mutation CreateCategoryRule($input: CreateCategoryRuleInput!) {
  createCategoryRule(input: $input) {
    ...CategoryRule
  }
}

mutation UpdateCategoryRule($input: UpdateCategoryRuleInput!) {
  updateCategoryRule(input: $input) {
    ...CategoryRule
  }
}

mutation DeleteCategoryRule($id: ID!) {
  deleteCategoryRule(id: $id)
}

mutation ReapplyRules($accounts: [ID!], $semanticAssign: Boolean! = true) {
  reapplyRules(accounts: $accounts, semanticAssign: $semanticAssign)
}
