fragment ListPortUsage on PortUsage {
  portKey
  index
  keyPath
  modifiers
  action {
    id
    name
    description
  }
}

fragment ListOutputStructureUsage on PortUsage {
  ...ListPortUsage
}

fragment ListInputStructureUsage on PortUsage {
  ...ListPortUsage
}

fragment ListInputInterfaceUsage on PortUsage {
  ...ListPortUsage
}

fragment ListOutputInterfaceUsage on PortUsage {
  ...ListPortUsage
}

fragment Structure on Structure {
  id: identifier
  identifier
  key
  label
  description
  package {
    key
  }
  service {
    id
    name
  }
  descriptors {
    id
    key
    type
    description
  }
  signals {
    ...SignalDeclaration
  }
  outputUsages {
    ...ListOutputStructureUsage
  }
  inputUsages {
    ...ListInputStructureUsage
  }
}

fragment ListStructure on Structure {
  id: identifier
  identifier
  key
  package {
    key
  }
}

fragment ListInterface on Interface {
  id: identifier
  identifier
  key
  package {
    key
  }
}

fragment Interface on Interface {
  id: identifier
  identifier
  key
  package {
    key
  }
  outputUsages {
    ...ListOutputInterfaceUsage
  }
  inputUsages {
    ...ListInputInterfaceUsage
  }
}

fragment StructurePackage on StructurePackage {
  id: key
  key
  structures {
    ...ListStructure
  }
  interfaces {
    ...ListInterface
  }
}

fragment ListStructurePackage on StructurePackage {
  id: key
  key
}
