query ListDescriptors(
  $filters: StructureDescriptorFilter
  $ordering: [StructureDescriptorOrder!] = []
  $pagination: OffsetPaginationInput
) {
  descriptors(filters: $filters, ordering: $ordering, pagination: $pagination) {
    ...ListDescriptor
  }
}

query GetDescriptor($id: ID!) {
  descriptor(id: $id) {
    ...Descriptor
  }
}

query ListHostedStructures(
  $filters: HostedStructureFilter
  $ordering: [HostedStructureOrder!] = []
  $pagination: OffsetPaginationInput
) {
  hostedStructures(filters: $filters, ordering: $ordering, pagination: $pagination) {
    ...ListHostedStructure
  }
}

query GetHostedStructure($id: ID!) {
  hostedStructure(id: $id) {
    ...ListHostedStructure
    structure {
      ...Structure
    }
  }
}
