/**
 * Edges into a module that are tolerated for now, each tagged with the step
 * of the module-boundaries plan that removes it. The boundary test fails on
 * any edge missing here AND on any entry here that no longer occurs, so this
 * list only ever shrinks. Keys are `from -> to` owners (see `ownerOf`).
 */
export const EDGE_ALLOWLIST: Record<string, string> = {
  "alpaka -> lok": "commit 6: @lok displays / useSelf",
  "alpaka -> rekuest": "commit 3/6: lib/ports + sections",
  "datalayer -> elektro": "commit 3: datalayer split",
  "datalayer -> kraph": "commit 3: datalayer split",
  "datalayer -> lok": "commit 3: datalayer split",
  "datalayer -> mikro": "commit 3: datalayer split",
  "datalayer -> rekuest": "commit 3: datalayer split",
  "dokuments -> datalayer": "commit 3: datalayer split",
  "dokuments -> lok": "commit 6: @lok displays / useSelf",
  "elektro -> datalayer": "commit 3: datalayer split",
  "elektro -> lok": "commit 6: @lok displays / useSelf",
  "fluss -> rekuest": "kept: fluss declares requires.services [\"rekuest\"]",
  "host:app -> alpaka": "commit 5: registries derived from MODULES",
  "host:app -> dokuments": "commit 5: registries derived from MODULES",
  "host:app -> elektro": "commit 5: registries derived from MODULES",
  "host:app -> fluss": "commit 5: registries derived from MODULES",
  "host:app -> kabinet": "commit 5: registries derived from MODULES",
  "host:app -> kraph": "commit 5: registries derived from MODULES",
  "host:app -> lok": "commit 5: registries derived from MODULES",
  "host:app -> lovekit": "commit 5: registries derived from MODULES",
  "host:app -> mikro": "commit 5: registries derived from MODULES",
  "host:app -> omeroark": "commit 5: registries derived from MODULES",
  "host:app -> rekuest": "commit 5: registries derived from MODULES",
  "host:blok -> lovekit": "commit 3/6: promote or invert",
  "host:blok -> rekuest": "commit 3/6: promote or invert",
  "host:command -> alpaka": "commit 5: registries derived from MODULES",
  "host:command -> elektro": "commit 5: registries derived from MODULES",
  "host:command -> kraph": "commit 5: registries derived from MODULES",
  "host:command -> lok": "commit 5: registries derived from MODULES",
  "host:command -> mikro": "commit 5: registries derived from MODULES",
  "host:command -> rekuest": "commit 5: registries derived from MODULES",
  "host:components -> alpaka": "commit 3/6: promote or invert",
  "host:components -> datalayer": "commit 3/6: promote or invert",
  "host:components -> elektro": "commit 3/6: promote or invert",
  "host:components -> kabinet": "commit 3/6: promote or invert",
  "host:components -> kraph": "commit 3/6: promote or invert",
  "host:components -> lok": "commit 3/6: promote or invert",
  "host:components -> rekuest": "commit 3/6: promote or invert",
  "host:dialogs -> alpaka": "commit 3/6: promote or invert",
  "host:dialogs -> kraph": "commit 3/6: promote or invert",
  "host:dialogs -> lok": "commit 3/6: promote or invert",
  "host:dialogs -> rekuest": "commit 3/6: promote or invert",
  "host:lib/arkitekt -> lok": "commit 3/6: promote or invert",
  "host:lib/arkitekt -> rekuest": "commit 3/6: promote or invert",
  "host:lib/export -> datalayer": "commit 3/6: promote or invert",
  "host:lib/export -> elektro": "commit 3/6: promote or invert",
  "host:lib/export -> mikro": "commit 3/6: promote or invert",
  "host:lib/export -> rekuest": "commit 3/6: promote or invert",
  "host:lib/taskhooks -> elektro": "commit 3/6: promote or invert",
  "host:lib/taskhooks -> rekuest": "commit 3/6: promote or invert",
  "host:providers -> alpaka": "commit 3/6: promote or invert",
  "host:providers -> datalayer": "commit 3/6: promote or invert",
  "host:providers -> kabinet": "commit 3/6: promote or invert",
  "host:providers -> kraph": "commit 3/6: promote or invert",
  "host:providers -> lok": "commit 3/6: promote or invert",
  "host:providers -> mikro": "commit 3/6: promote or invert",
  "host:providers -> rekuest": "commit 3/6: promote or invert",
  "host:settings -> lok": "commit 5: registries derived from MODULES",
  "kabinet -> rekuest": "commit 3/6: lib/ports + sections",
  "kraph -> alpaka": "commit 6: section surfaces",
  "kraph -> datalayer": "commit 3: datalayer split",
  "kraph -> fluss": "commit 6: section surfaces",
  "kraph -> lok": "commit 6: @lok displays / useSelf",
  "kraph -> rekuest": "commit 3/6: lib/ports + sections",
  "lok -> datalayer": "commit 3: datalayer split",
  "lok -> kraph": "commit 6: section surfaces",
  "lok -> rekuest": "commit 3/6: lib/ports + sections",
  "lovekit -> rekuest": "commit 3/6: lib/ports + sections",
  "mikro -> datalayer": "commit 3: datalayer split",
  "mikro -> kraph": "commit 6: section surfaces",
  "mikro -> lok": "commit 6: @lok displays / useSelf",
  "omeroark -> kraph": "commit 6: section surfaces",
  "rekuest -> datalayer": "commit 3: datalayer split",
  "rekuest -> fluss": "commit 6: section surfaces",
  "rekuest -> lok": "commit 6: @lok displays / useSelf",
};
