import {
  Activity,
  AlertCircle,
  AlertTriangle,
  Archive,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  AtSign,
  Ban,
  BarChart3,
  Bell,
  Bookmark,
  Box,
  Braces,
  Calendar,
  Camera,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronsUpDown,
  Circle,
  CircleDot,
  Clipboard,
  Clock,
  Cloud,
  Code,
  Cog,
  Copy,
  Cpu,
  Database,
  Download,
  Edit,
  ExternalLink,
  Eye,
  EyeOff,
  File,
  FileText,
  Filter,
  Flag,
  Folder,
  FolderOpen,
  Gauge,
  Globe,
  Grid3x3,
  Hash,
  Heart,
  HelpCircle,
  History,
  Home,
  Image,
  Inbox,
  Info,
  Key,
  Layers,
  LayoutDashboard,
  Link,
  List,
  Loader2,
  Lock,
  LogIn,
  LogOut,
  Mail,
  Map,
  Maximize2,
  Menu,
  MessageCircle,
  Microscope,
  Minimize2,
  Minus,
  Monitor,
  MoreHorizontal,
  MoreVertical,
  Move,
  Network,
  Package,
  Paperclip,
  Pause,
  Pencil,
  Play,
  Plus,
  Power,
  RefreshCw,
  Rocket,
  RotateCcw,
  Save,
  Search,
  Send,
  Server,
  Settings,
  Share2,
  Shield,
  SkipForward,
  Sliders,
  Square,
  Star,
  StopCircle,
  Table,
  Tag,
  Terminal,
  ThumbsDown,
  ThumbsUp,
  Trash2,
  TrendingDown,
  TrendingUp,
  Upload,
  User,
  UserPlus,
  Users,
  Video,
  Wand2,
  Workflow,
  Wrench,
  X,
  XCircle,
  Zap,
  ZoomIn,
  ZoomOut,
  type LucideIcon,
} from 'lucide-react';
import * as z from 'zod';
import {createBlokComponent, useBlok, useValue} from '../runtime';
import {classNameSchema, numberSchema} from './shared';

/**
 * The icons a blok payload may name.
 *
 * Deliberately an explicit allowlist rather than a dynamic lookup over
 * `lucide-react`: the named imports are what makes the bundle carry only these
 * ~120 glyphs instead of the whole icon set, and the enum derived from the keys
 * is what tells an author (via the registered catalog) which names exist.
 *
 * Adding an icon means adding the import and the entry — both in this file.
 */
export const BLOK_ICONS = {
  activity: Activity,
  'alert-circle': AlertCircle,
  'alert-triangle': AlertTriangle,
  archive: Archive,
  'arrow-down': ArrowDown,
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  'arrow-up': ArrowUp,
  'at-sign': AtSign,
  ban: Ban,
  'bar-chart': BarChart3,
  bell: Bell,
  bookmark: Bookmark,
  box: Box,
  braces: Braces,
  calendar: Calendar,
  camera: Camera,
  check: Check,
  'check-circle': CheckCircle2,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'chevron-up': ChevronUp,
  'chevrons-up-down': ChevronsUpDown,
  circle: Circle,
  'circle-dot': CircleDot,
  clipboard: Clipboard,
  clock: Clock,
  cloud: Cloud,
  code: Code,
  cog: Cog,
  copy: Copy,
  cpu: Cpu,
  database: Database,
  download: Download,
  edit: Edit,
  'external-link': ExternalLink,
  eye: Eye,
  'eye-off': EyeOff,
  file: File,
  'file-text': FileText,
  filter: Filter,
  flag: Flag,
  folder: Folder,
  'folder-open': FolderOpen,
  gauge: Gauge,
  globe: Globe,
  grid: Grid3x3,
  hash: Hash,
  heart: Heart,
  'help-circle': HelpCircle,
  history: History,
  home: Home,
  image: Image,
  inbox: Inbox,
  info: Info,
  key: Key,
  layers: Layers,
  layout: LayoutDashboard,
  link: Link,
  list: List,
  loader: Loader2,
  lock: Lock,
  'log-in': LogIn,
  'log-out': LogOut,
  mail: Mail,
  map: Map,
  maximize: Maximize2,
  menu: Menu,
  message: MessageCircle,
  microscope: Microscope,
  minimize: Minimize2,
  minus: Minus,
  monitor: Monitor,
  'more-horizontal': MoreHorizontal,
  'more-vertical': MoreVertical,
  move: Move,
  network: Network,
  package: Package,
  paperclip: Paperclip,
  pause: Pause,
  pencil: Pencil,
  play: Play,
  plus: Plus,
  power: Power,
  refresh: RefreshCw,
  rocket: Rocket,
  'rotate-ccw': RotateCcw,
  save: Save,
  search: Search,
  send: Send,
  server: Server,
  settings: Settings,
  share: Share2,
  shield: Shield,
  'skip-forward': SkipForward,
  sliders: Sliders,
  square: Square,
  star: Star,
  stop: StopCircle,
  table: Table,
  tag: Tag,
  terminal: Terminal,
  'thumbs-down': ThumbsDown,
  'thumbs-up': ThumbsUp,
  trash: Trash2,
  'trending-down': TrendingDown,
  'trending-up': TrendingUp,
  upload: Upload,
  user: User,
  'user-plus': UserPlus,
  users: Users,
  video: Video,
  wand: Wand2,
  workflow: Workflow,
  wrench: Wrench,
  x: X,
  'x-circle': XCircle,
  zap: Zap,
  'zoom-in': ZoomIn,
  'zoom-out': ZoomOut,
} as const satisfies Record<string, LucideIcon>;

export type BlokIconName = keyof typeof BLOK_ICONS;

const ICON_NAMES = Object.keys(BLOK_ICONS) as [BlokIconName, ...BlokIconName[]];

export const iconNameSchema = z
  .enum(ICON_NAMES)
  .optional()
  .describe(`Icon name. One of: ${ICON_NAMES.join(', ')}.`);

/** Renders an icon prop inline, or nothing when the name is absent/unknown. */
export const renderIcon = (name: unknown, className?: string) => {
  if (typeof name !== 'string' || !(name in BLOK_ICONS)) {
    return null;
  }

  const IconComponent = BLOK_ICONS[name as BlokIconName];
  return <IconComponent className={className ?? 'size-4'} />;
};

export const Icon = createBlokComponent(
  {
    name: 'Icon',
    schema: z
      .object({
        name: iconNameSchema,
        size: numberSchema.describe('Pixel size. Defaults to the surrounding text size.'),
        className: classNameSchema,
      })
      .describe('A lucide icon.'),
  },
  ({component, schema}) => {
    const blok = useBlok(component, schema);
    const name = useValue(blok.name);
    const size = useValue(blok.size);
    const className = useValue(blok.className);

    if (!name) {
      return null;
    }

    const IconComponent = BLOK_ICONS[name];
    return <IconComponent size={size} className={className ?? (size ? undefined : 'size-4')} />;
  },
);

export const iconBlokComponents = [Icon];
